version: '3'
services:
  api:
    build:
      context: ..
      dockerfile: docker/build/Django
    volumes:
      - ../:/pokemondb
    depends_on:
      - postgres
    ports:
      - "8000:8000"


  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=ash
      - POSTGRES_DB=pokemondb
